<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_usuarios  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["CustomAdd"]=true;

		$this->events["ListQuery"]=true;

		$this->events["ListGetRowCount"]=true;

		$this->events["ListFetchArray"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		

$sql = DB::PrepareSQL("select * from public.abm_users(':1',':2',':3'); END;",$values["login"], $values["password"] , $values["rol"]);
DB::Query($sql);


// Place event code here.
// Use "Add Action" button to add code snippets.

return false;
;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Custom Query
function ListQuery($searchObj, $orderBy, $howOrderBy, $masterTable, $masterKeysReq, $selectedRecord, $pageSize, $myPage, $pageObject)
{

		
return DB::Query("select * from sp_verusers");
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ListQuery

		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Get Row Count
function ListGetRowCount($searchObj, $masterTable, $masterKeysReq, $selectedRecords, $pageObject)
{

		
return DBLookup("select count(*) from modalidad");
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ListGetRowCount

		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Fetch records
function ListFetchArray(&$rs, $pageObject)
{

		
return $rs->fetchAssoc();

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ListFetchArray

		
		
		
		
		
		



}
?>
